require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/LineLength:
  Max: 130
  Exclude:
    - config/initializers/devise.rb

Rails:
  Enabled: true


Layout/CommentIndentation:
  Exclude:
    - spec/spec_helper.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/initializers/devise.rb

Metrics/MethodLength:
  Max: 15

# From Ruby 3.4 this is the default
# this code base will be updated to that version
Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

# No documentation by default
Style/Documentation:
  Enabled: false



Style/ClassAndModuleChildren:
   Exclude:
     - app/controllers/users/*_controller.rb

RSpec/MultipleExpectations:
  Max: 3
